-- Your SQL goes here
create table if not exists prisons
(
    prison_id  VARCHAR(11) NOT NULL primary key,
    gender  varchar(1)   not null, -- M = Male, F = Female
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    nick_name VARCHAR(100) NOT NULL,
    birth_day timestamp    not null,
    picture_paht VARCHAR(100) NOT NULL,
    location VARCHAR(50) NOT NULL,
    prison_type smallint NOT NULL DEFAULT 0,
    remark   VARCHAR(200) NOT NULL,
    id_card   VARCHAR(20) NOT NULL,
    address_no VARCHAR(20) NOT NULL,
    moo VARCHAR(20) NOT NULL,
    subdistric VARCHAR(50) NOT NULL,
    distric VARCHAR(50) NOT NULL,
    province  VARCHAR(70) NOT NULL,
    nation VARCHAR(100) NOT NULL,
    race  VARCHAR(50) NOT NULL,
    nationality VARCHAR(50) NOT NULL,
    religion  VARCHAR(50) NOT NULL,
    blame VARCHAR(200) NOT NULL,
    education VARCHAR(200) NOT NULL,
    edu_institution VARCHAR(200) NOT NULL,
    edu_address1 VARCHAR(200) NOT NULL,
    status  VARCHAR(70) NOT NULL,
    child  smallint NOT NULL DEFAULT 0,
    sibling smallint NOT NULL DEFAULT 0,
    child_in_a_child smallint NOT NULL DEFAULT 0,
    home_owner VARCHAR(30) NOT NULL,
    stay_address_no VARCHAR(20) NOT NULL,
    stay_moo VARCHAR(20) NOT NULL,
    stay_subdistric VARCHAR(50) NOT NULL,
    stay_distric VARCHAR(50) NOT NULL,
    stay_province  VARCHAR(70) NOT NULL,
    occupation  VARCHAR(100) NOT NULL,
    income VARCHAR(50) NOT NULL,
    history_punish VARCHAR(100) NOT NULL,
    history_punish_year smallint NOT NULL DEFAULT 0,
    history_punish_month smallint NOT NULL DEFAULT 0,
    history_punish_day smallint NOT NULL DEFAULT 0,
    prove_pass_num smallint NOT NULL DEFAULT 0,
    cur_num smallint NOT NULL DEFAULT 0,
    created_at   timestamp    not null,
    updated_at   timestamp
    );
create index prisons_by_first_name_last_name on prisons(first_name, last_name);

